### ISSUE TITLE
Norton SONAR 보호로 인한 앱의 예상치 못한 중지

### ISSUE THREAD

**Issue by seia-soto** [sokcuri/TwimgSpeedPatch#1]
현재 Norton SONAR에 새 앱으로 등록이 된 것 같습니다만 일부 시스템에 취약점을 제공한다고 보여집니다. 그리고 앱이 시작 후 패치 버튼을 클릭한 이후 강제종료되었으며 그 이후에 바로 새로운 바이러스가 검출되었다며 메세지가 보여졌습니다. 혹시 해결하실 수 있으면 해결 부탁드립니다.

- Windows 10 x64 1809(2019-05-21) 17763.529 - LTSC

[Norton SONAR 데이터베이스 취약점 유형: SONAR.Heur.SBG1!gen4](https://www.symantec.com/security-center/writeup/2015-120721-4225-99?ssdcat=118&vid=4294923089&product=Norton+AntiVirus&version=22.17.2.46&plang=sym%3aKN&layouttype=ESD&buildname=Retail&heartbeatID=35D7012F-18EF-46C0-B997-D8DF0E50135F&eapenabled=false&env=prod&vendorid=1000&plid=779&plgid=35&skup=21364918&skum=21376863&skuf=21364927&endpointid=35D7012F-18EF-46C0-B997-D8DF0E50135F&partnerid=1000&lic_type=16&lic_attr=17059858&psn=GWYGQJJ2X8TM&puid=5039&templatecat=SBU_W_1000_5039_NAV_ESD_2&schemacat=SBU_W&schemaver=1.0.0.0&olpchannel=SESD&osvers=10.0&oslocale=iso%3aKOR&oslang=iso%3aKOR&os=windows)

![image](https://user-images.githubusercontent.com/30369714/59150350-eb406100-8a5c-11e9-9ab1-e160eac31123.png)

![image](https://user-images.githubusercontent.com/30369714/59150347-de237200-8a5c-11e9-89b0-2e0ed10360fb.png)

![image](https://user-images.githubusercontent.com/30369714/59150345-d82d9100-8a5c-11e9-94c1-d613a35c8986.png)

**Comment by seia-soto** [comment]
Norton false positive 보고서 올렸습니다 :>

**Comment by sokcuri** [comment]
저도 노턴쪽에 리포트 작성해서 올렸습니다

**Comment by sokcuri** [comment]
답신이 왔습니다.

We have processed your submission (Tracking #43254916) and your submission is now closed. The following is a report of our findings for the files in your submission:

## Submission Summary
### Files Submitted
| # | Filename | MD5 | Determination | Signature Protection Name | RR Seq |
| -- | -- | -- | -- | -- | -- |
| 1 | TwimgSpeedPatch_2019.6.1.zip | cefe9b3863adbee48994fd3e2fe69565 | Archive | N/A | N/A |
| 2 | TwimgSpeedPatch.exe | 71e1e717e98c043502b42ddb043ba6b9 | Threat artifact | N/A | N/A |

### Developer Notes:

1. TwimgSpeedPatch_2019.6.1.zip is a container file e.g. archive, email 
2. TwimgSpeedPatch.exe is not malicious itself, but may be an artifact of a threat. 

## Assessment
File 1:	TwimgSpeedPatch_2019.6.1.zip
MD5:	cefe9b3863adbee48994fd3e2fe69565
SHA256:	2616d7cb64dc7176e5c72f84fe2d8b5157488404db9ea32770ba301948c4a229
Determination:	See Dev Notes.
Submission Detail:	Please see the developer notes.

---
File 2:	TwimgSpeedPatch.exe
MD5:	71e1e717e98c043502b42ddb043ba6b9
SHA256:	29fd592e4724890b32a92151b180c7110e54669d3b51227674c410186009f030
Determination:	See Dev Notes.
Submission Detail:	Please see the developer notes.

---
This message was generated by Symantec Security Response automation. 

More information on Threat Artifact determinations can be found in the article: What is a Threat Artifact? 

Should you have any questions about your submission, please contact our regional technical support from the Symantec Web site and give them the tracking number included in this message. 

Symantec Technical Support 
http://support.symantec.com
Sincerely, 
Symantec Security Response

**Comment by sokcuri** [comment]
@Seia-Soto 취약점이 있다는건 아무래도 Hosts 파일을 건드리니깐 그런것 같네요. 별 문제 없어보입니다. 지금은 노턴에서 안잡나요?

**Comment by seia-soto** [comment]
![image](https://user-images.githubusercontent.com/30369714/59162374-caded800-8b2a-11e9-9bdc-1e3e89997ae6.png)

일단은 Norton에서 처리는 한 것 같습니다만 SONAR 커뮤니티 평판에 들어갈려면 시간이 좀 필요한가 봅니다.

**Comment by sokcuri** [comment]
문제 생기면 다시 열어주세요. 감사합니다
