### ISSUE TITLE
Windows 10 영문 환경에서 UI 비율 문제

### ISSUE THREAD

**Issue by enusan-yn** [sokcuri/TwimgSpeedPatch#3]
Windows 10 시스템 언어가 영어인 환경에서 UI 비율이 마치 16:9에서 4:3으로 된 듯 좁혀져서 렌더링 됩니다. 백그라운드 이미지가 강제로 늘어지고, 텍스트 스트링 일부가 짤려 나옵니다.

- Windows 10 x64 1903 (18362.116)

- Korean Supplement font 제거된 상태 (굴림, 돋움, 궁서가 시스템에서 제거됨)
![image](https://user-images.githubusercontent.com/5804598/59353389-d5cd7e80-8d5d-11e9-994e-a77b140c9b59.png)

**Comment by enusan-yn** [comment]
- https://six605.tistory.com/528

WinForms의 AutoScaleMode과 관련한 문제로 보입니다.

**Comment by sokcuri** [comment]
수정했습니다. 2019.6.2 버전에서도 동일한 문제가 발생하는지 확인해주세요

**Comment by enusan-yn** [comment]
![image](https://user-images.githubusercontent.com/5804598/59360362-e9cbad00-8d6a-11e9-8587-46ccbd29bf00.png)

해결됬습니다.

**Comment by sokcuri** [comment]
감사합니다!
